/** @jsx jsx */
import { jsx } from "theme-ui"
import { RiRssLine } from "react-icons/ri"

// Links to the combined RSS feed generated by gatsby-plugin-feed (/rss.xml).
const RssLink = () => (
  <a
    href="/rss.xml"
    aria-label="RSS feed"
    title="RSS feed"
    target="_blank"
    rel="noopener noreferrer"
    sx={{
      display: "flex",
      alignItems: "center",
      color: "#fff",
      fontSize: "25px",
      lineHeight: 1,
      "&:hover": { color: "rgba(255, 255, 255, 0.8)" },
    }}
  >
    <RiRssLine />
  </a>
)

export default RssLink
